/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColSetting: typeof import('./src/components/ColSetting.vue')['default']
    CountDown: typeof import('./src/components/CountDown.vue')['default']
    CustomDatePicker: typeof import('./src/components/CustomDatePicker.vue')['default']
    CustomImport: typeof import('./src/components/CustomImport.vue')['default']
    CustomTable: typeof import('./src/components/CustomTable.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ErrorLog: typeof import('./src/components/ErrorLog/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LgtBreadcrumb: typeof import('./src/components/lgt-breadcrumb/index.vue')['default']
    LgtHamburger: typeof import('./src/components/lgt-hamburger/index.vue')['default']
    MulElSelect: typeof import('./src/components/MulElSelect.vue')['default']
    MulVxeSelect: typeof import('./src/components/MulVxeSelect.vue')['default']
    NxScrollPane: typeof import('./src/components/nx-scroll-pane/index.vue')['default']
    QuarterDatePicker: typeof import('./src/components/QuarterDatePicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
